inherit_from:
  - https://raw.githubusercontent.com/trinistr/rubocop-config/main/rubocop.yml

plugins:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-thread_safety
  - rubocop-yard

# These make no sense for a single-class library.
Metrics/ClassLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/StaticClass:
  # Cop triggers on subfiles, even though it is wrong.
  Enabled: false
RSpec/SpecFilePathFormat:
  # Grouping is done by source files, not constants or methods.
  Enabled: false
