inherit_from:
  - https://raw.githubusercontent.com/trinistr/rubocop-config/main/rubocop.yml

plugins:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-thread_safety
  - rubocop-yard

# This makes no sense for a single-class library.
Metrics/ClassLength:
  Enabled: false

# Cop triggers on subfiles, even though it is wrong.
Style/StaticClass:
  Enabled: false
