type vector_type = VectorNumber
type real_number = (Integer | Float | Rational | BigDecimal)

type in_value_type = untyped
type unit_type = untyped
type coefficient_type = real_number

type list[T] = Array[T]

type plain_vector_type = Hash[unit_type, coefficient_type]
type units_list_type = list[unit_type]
type coefficients_list_type = list[coefficient_type]
type each_value_type = [unit_type, coefficient_type]

type options_type = Hash[Symbol, untyped]
