# A class to add together anything.
class VectorNumber
  # ---- Generic types ----
  type real_number = Integer | Float | Rational | BigDecimal

  type in_value_type = untyped
  type unit_type = untyped
  type coefficient_type = real_number

  type list[T] = Array[T]

  type vector_instance = VectorNumber
  type plain_instance = Hash[unit_type, coefficient_type]
  type units_list_type = list[unit_type]
  type coefficients_list_type = list[coefficient_type]
  type each_value_type = [unit_type, coefficient_type]

  # ---- Constants ----

  VERSION: String

  NUMERIC_UNITS: list[SpecialUnit]
  R: SpecialUnit
  I: SpecialUnit

  # ---- Public methods ----

  def self.[]: (*unit_type values) -> vector_instance

  def self.numeric_unit?: (unit_type unit) -> bool

  def size: -> Integer

  def initialize:
    (?(units_list_type | plain_instance | vector_instance)? values)
    ?{ (coefficient_type coefficient) -> coefficient_type }
    -> void

  def +@: () -> self
  alias dup +@

  def clone: (?freeze: bool?) -> self

  private

  @size: Integer
  @data: plain_instance

  def new: () { (coefficient_type value) -> coefficient_type } -> vector_instance
         | (in_value_type) { (coefficient_type value) -> coefficient_type } -> vector_instance
         | () -> vector_instance
         | (in_value_type) -> vector_instance

  def real_number?: (real_number value) -> true
                  | (vector_instance) -> bool
                  | (in_value_type value) -> false

  def initialize_from: ((units_list_type | plain_instance | vector_instance)? values) -> void

  def add_value_to_data: ((vector_instance | Numeric | unit_type) value) -> void

  def add_numeric_value_to_data: (Numeric value) -> void

  def add_vector_to_data: ((vector_instance | plain_instance) vector) -> void

  def apply_transform: () ?{ (coefficient_type value) -> coefficient_type } -> void

  def finalize_contents: () -> void
end

# Methods for performing actual math.
class VectorNumber
  def coerce: (in_value_type) -> [vector_instance, self]

  def -@: () -> vector_instance
  alias neg -@

  def +: (in_value_type) -> vector_instance
  alias add +

  def -: (in_value_type) -> vector_instance
  alias sub -

  def *: (real_number | vector_instance) -> vector_instance
  alias mult *

  def /: (real_number | vector_instance) -> vector_instance
  alias quo /

  def fdiv: (real_number | vector_instance) -> vector_instance

  def div: (real_number | vector_instance) -> vector_instance

  def ceildiv: (real_number | vector_instance) -> vector_instance

  def %: (real_number | vector_instance) -> vector_instance
  alias modulo %

  def divmod: (real_number | vector_instance) -> [vector_instance, vector_instance]

  def remainder: (real_number | vector_instance) -> vector_instance

  private

  def check_divisibility: (real_number | vector_instance) -> void
end

# Various mathematical operations that are also conversions.
class VectorNumber
  def truncate: (?Integer) -> vector_instance

  def ceil: (?Integer) -> vector_instance

  def floor: (?Integer) -> vector_instance

  def round: (?Integer, ?half: (:up | :down | :even)) -> vector_instance
end

# Methods for converting to different number classes.
class VectorNumber
  def real: () -> real_number

  def imaginary: () -> real_number
  alias imag imaginary

  def to_i: () -> Integer
  alias to_int to_i

  def to_f: () -> Float

  def to_r: () -> Rational

  def to_d: (?Integer?) -> BigDecimal

  def to_c: () -> Complex

  private

  def raise_convert_error: (Class) -> void
end

# Methods for enumeration and hash-like operations
class VectorNumber
  include _Each[each_value_type]
  include Enumerable[each_value_type]

  def each: () { (each_value_type) -> void } -> self
          | () -> Enumerator[each_value_type, VectorNumber]
          | ...
  alias each_pair each

  def units: () -> units_list_type
  alias keys units

  def coefficients: () -> coefficients_list_type
  alias values coefficients

  def coefficients_at: (*unit_type units) -> coefficients_list_type
  alias values_at coefficients_at

  def to_h: () ?{ (unit_type, coefficient_type) -> each_value_type } -> plain_instance

  def []: (unit_type unit) -> coefficient_type

  def assoc: (unit_type unit) -> [unit_type, coefficient_type]

  def dig: (*unit_type units) -> coefficient_type

  def fetch: (unit_type unit) -> coefficient_type
           | [X] (unit_type unit, X default_value) -> (coefficient_type | X)
           | [X] (unit_type unit) { (unit_type unit) -> X } -> (coefficient_type | X)

  def fetch_coefficients: (*unit_type units) -> coefficients_list_type
                        | [X] (*unit_type units) { (unit_type unit) -> X } -> list[(coefficient_type | X)]
  alias fetch_values fetch_coefficients

  def unit?: (unit_type unit) -> bool
  alias key? unit?

  def transform_coefficients: () { (coefficient_type value) -> coefficient_type } -> vector_instance
                            | (Hash[coefficient_type, coefficient_type] mapping) ?{ (coefficient_type unit) -> coefficient_type } -> vector_instance
                            | () -> Enumerator[coefficient_type, VectorNumber]
  alias transform_values transform_coefficients

  def transform_units: () { (unit_type unit) -> unit_type } -> vector_instance
                     | (Hash[unit_type, unit_type] mapping) ?{ (unit_type unit) -> unit_type } -> vector_instance
                     | () -> Enumerator[unit_type, VectorNumber]
  alias transform_keys transform_units
end

# Methods for comparing with other numbers.
class VectorNumber
  def ==: (in_value_type other) -> bool

  def eql?: (in_value_type other) -> bool

  def hash: () -> Integer

  def <=>: (in_value_type other) -> Integer?
end

# Methods for querying state of the number.
# Mostly modeled after {::Complex}.
class VectorNumber
  def numeric?: (?Integer) -> bool

  def nonnumeric?: (?Integer) -> bool

  def finite?: () -> bool

  def infinite?: () -> Integer?

  def zero?: () -> bool

  def nonzero?: () -> self?

  def positive?: () -> bool

  def negative?: () -> bool

  def real?: () -> false

  def integer?: () -> false
end

# Methods and options for string representation.
class VectorNumber
  MULT_STRINGS: Hash[Symbol, String]

  def to_s: (?mult: (Symbol | String)) { (unit_type, coefficient_type, ?Integer index, ?String operator) -> String } -> String

  def inspect: () -> String

  private

  def build_string: (String operator) -> String
                  | (String operator) { (unit_type, coefficient_type, ?Integer index, ?String operator) -> String } -> String

  def value_to_s: (unit_type unit, coefficient_type coefficient, String operator) -> String

  def fill_breakable: (PP pp) -> void
end

# Vector operations.
class VectorNumber
  def abs: () -> Float
  alias magnitude abs
  alias euclidean_norm abs

  def abs2: () -> Float

  def p_norm: (Numeric power) -> Numeric

  def maximum_norm: () -> Numeric

  def subspace_basis: () -> Array[vector_instance]

  def uniform_vector: () -> vector_instance

  def unit_vector: () -> vector_instance

  def dot_product: (in_value_type other) -> coefficient_type
  alias inner_product dot_product
  alias scalar_product dot_product

  def angle: (in_value_type other) -> Float

  def scalar_projection: (in_value_type other) -> coefficient_type

  def vector_projection: (in_value_type other) -> vector_instance

  def scalar_rejection: (in_value_type other) -> coefficient_type

  def vector_rejection: (in_value_type other) -> vector_instance

  private

  def has_direction?: (?in_value_type vector) -> void
end

class VectorNumber
  # Refinements of Numeric classes to better work with VectorNumber and similar classes.
  module NumericRefinements
    module CommutativeShuttle
      def <=>: (in_value_type other) -> Integer?
    end

    module BigDecimalToD
      def BigDecimal: (untyped value, exception: bool) -> BigDecimal?
                    | (untyped value, Integer ndigits, exception: bool) -> BigDecimal?
    end
  end
end

class VectorNumber
  # Class for representing special numerical units.
  class SpecialUnit
    def initialize: (Object unit, String text) -> void

    def to_s: () -> String
    
    def inspect: () -> String
  end
end
