name: CI

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        fail-fast: false
        ruby:
          - '3.1.0'
          - '3.1'
          - '3.2'
          - '3.3'
          - head
          - jruby
          - jruby-head
          - truffleruby
          - truffleruby-head

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        # Mititage ffi 1.17 fail with binary gem.
        rubygems: '3.3.22'
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake
