name: CRuby

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.1.0'
          - '3.1'
          - '3.2'
          - '3.3'
          - 'head'
        experimental: [false]
    continue-on-error: ${{ matrix.experimental }}
    env:
      BUNDLE_WITHOUT: 'development'
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake
