name: JRuby

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - jruby
          - jruby-head
        experimental: [true]
    continue-on-error: ${{ matrix.experimental }}
    env:
      BUNDLE_WITHOUT: 'default:development'
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake
