name: JRuby

on:
  workflow_call:

jobs:
  test:
    name: ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
        - jruby
        - jruby-head
        experimental: [true]
    continue-on-error: ${{ matrix.experimental }}
    env:
      BUNDLE_WITHOUT: 'linting:optional:development'
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run RSpec
      run: bundle exec rake spec
