name: JRuby
permissions:
  contents: read
on:
  workflow_call:
jobs:
  test:
    name: ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
        - jruby
        - jruby-head
        experimental: [true]
    continue-on-error: ${{ matrix.experimental }}
    env:
      # JRuby complains about loading bigdecimal, but the gem can't be built.
      BUNDLE_ONLY: "default:test:optional"
    steps:
    - uses: actions/checkout@v5
      with:
        persist-credentials: false
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run RSpec
      run: bundle exec rake spec
